home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path("", views.home, name="home"),
]

recipes/urls.py
from django.urls import path
from . import views

app_name = "recipes"
urlpatterns = [
    path("", views.CategoryListView.as_view(), name="category_list"),
    path("category/<int:pk>/", views.RecipeListView.as_view(), name="recipe_list"),
    path(
        "category/none/", views.RecipeListView.as_view(), name="recipe_list_no_category"
    ),
    path("category/add/", views.CategoryCreateView.as_view(), name="category_add"),
    path("recipe/<int:pk>/", views.RecipeDetailView.as_view(), name="recipe_detail"),
    path("recipe/add/", views.RecipeCreateView.as_view(), name="recipe_add"),
    path("all/", views.PrintView.as_view(), name="all_recipes"),
    path("search/", views.RecipeListView.as_view(), name="search_results"),
]

valhalla/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'home.views.error_404'
handler500 = 'home.views.error_500'

urlpatterns = [
    path('mithrun/', admin.site.urls),
    path('', include('home.urls')),
    path('senshi/', include('recipes.urls'))
]

home/models.py
from django.db import models

# Create your models here.

recipes/models.py
from django.db import models
from django.core.validators import MinLengthValidator

"""
Model to store recipe categories ("Desserts", "Soups", etc.)
"""


class Category(models.Model):
    name = models.CharField(
        max_length=200,
        validators=[
            MinLengthValidator(2, "El nombre debe ser de más de dos caracteres")
        ],
        verbose_name="Nombre",
    )
    order = models.IntegerField(default=0, verbose_name="Orden personalizado")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Categoría"
        verbose_name_plural = "Categorías"
        ordering = ["order"]

    def __str__(self):
        return self.name


"""
Model to store ingredients
"""


class Ingredient(models.Model):
    name = models.CharField(
        max_length=100,
        validators=[
            MinLengthValidator(2, "El nombre debe ser de más de dos caracteres")
        ],
        verbose_name="Nombre",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Ingrediente"
        verbose_name_plural = "Ingredientes"
        ordering = ["name"]

    def __str__(self):
        return self.name


"""
Model to store recipes
"""


class Recipe(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[
            MinLengthValidator(2, "El nombre debe ser de más de dos caracteres")
        ],
        verbose_name="Título",
    )
    ingredients = models.ManyToManyField(
        Ingredient, through="RecipeIngredient", blank=True
    )
    body = models.TextField(blank=True, null=True, verbose_name="Cuerpo")
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="Categoría",
    )
    related_recipes = models.ManyToManyField(
        "self",
        related_name="referenced_by",
        symmetrical=False,
        blank=True,
        verbose_name="Recetas relacionadas",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Receta"
        verbose_name_plural = "Recetas"
        ordering = ["title"]

    def __str__(self):
        return self.title


"""
Model to relate recipes to ingredients
"""


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.PROTECT)
    main_quantity = models.DecimalField(max_digits=7, decimal_places=3)
    main_unit = models.CharField(max_length=20)
    second_quantity = models.DecimalField(
        max_digits=7, decimal_places=3, blank=True, null=True
    )
    second_unit = models.CharField(max_length=20, blank=True)

home/views.py
from django.shortcuts import render


def home(request):
    return render(
        request,
        "home/homepage.html",
        {
            "pages": [
                {"url": "senshi/", "name": "Mis recetas"},
                {"url": "mithrun/", "name": "Administrar el sitio"},
            ],
            "header_text": "Bienvenidos",
        },
    )


def error_404(request, exception):
    return render(request, "home/error_404.html", status=404)


def error_500(request):
    return render(request, "home/error_500.html", status=500)

recipes/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic.edit import CreateView
from . import models


class CategoryListView(View):
    template_name = "recipes/category_list.html"

    def get(self, request):
        categories = models.Category.objects.all()
        return render(
            request,
            self.template_name,
            {
                "category_list": map(
                    lambda c: {
                        "id": c.id,
                        "name": c.name,
                        "count": models.Recipe.objects.filter(category=c).count(),
                    },
                    categories,
                ),
                "no_category_count": models.Recipe.objects.filter(
                    category=None
                ).count(),
                "header_text": "Mis recetas",
            },
        )


class CategoryCreateView(CreateView):
    model = models.Category
    fields = "__all__"
    success_url = reverse_lazy("recipes:category_list")

    def get_context_data(self, **kwargs):
        ctx = super(CategoryCreateView, self).get_context_data(**kwargs)
        ctx["header_text"] = "Añadir categoría"
        return ctx


class RecipeListView(View):
    template_name = "recipes/recipe_list.html"

    def get(self, request, pk=None):
        if pk:
            category = get_object_or_404(models.Category, id=pk)
            return render(
                request,
                self.template_name,
                {
                    "category": category,
                    "recipe_list": models.Recipe.objects.filter(category=category),
                    "header_text": category.name,
                },
            )
        if request.path == reverse("recipes:search_results"):
            search_str = request.GET.get("query", "")
            return render(
                request,
                self.template_name,
                {
                    "recipe_list": models.Recipe.objects.filter(
                        title__icontains=search_str
                    ),
                    "header_text": "Resultados",
                    "query": search_str,
                },
            )
        return render(
            request,
            self.template_name,
            {
                "recipe_list": models.Recipe.objects.filter(category=None),
                "header_text": "Sin categoría",
            },
        )


class RecipeDetailView(View):
    template_name = "recipes/recipe_detail.html"

    def get(self, request, pk):
        recipe = get_object_or_404(models.Recipe, id=pk)
        return render(
            request,
            self.template_name,
            {"recipe": recipe, "header_text": recipe.title},
        )


class RecipeCreateView(CreateView):
    model = models.Recipe
    fields = "__all__"
    success_url = reverse_lazy("recipes:category_list")

    def get_context_data(self, **kwargs):
        ctx = super(RecipeCreateView, self).get_context_data(**kwargs)
        ctx["header_text"] = "Añadir receta"
        return ctx


class PrintView(View):
    template_name = "recipes/all_recipes.html"

    def get(self, request):
        categories = models.Category.objects.all()
        return render(
            request,
            self.template_name,
            {
                "category_list": map(
                    lambda c: {
                        "id": c.id,
                        "name": c.name,
                        "recipes": models.Recipe.objects.filter(category=c),
                    },
                    categories,
                ),
                "no_category_list": models.Recipe.objects.filter(category=None),
            },
        )

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}

      {% endblock %}
    </title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
  </head>
  <body>
    <div class="container-fluid">
      <!-- HEADER -->
      <div class="container-fluid">
        <div class="row align-items-center">
          <div class="col-2 d-flex justify-content-center">
            {% block header_left %}

            {% endblock %}
          </div>
          <div class="col-8">
            <h1 class="display-1 text-center d-none d-md-block">{{ header_text }}</h1>
            <!-- Title for small screens -->
            <h1 class="display-5 text-center d-md-none">{{ header_text }}</h1>
          </div>
          <div class="col-2 d-flex justify-content-center">
            {% block header_right %}

            {% endblock %}
          </div>
        </div>
      </div>
      <!-- CONTENT -->
      {% block content %}

      {% endblock %}
    </div>
  </body>
</html>

home/templates/home/error_404.html
{% extends 'base.html' %}
{% block title %}
  Valhalla 404
{% endblock %}
{% block content %}
  <div class="container d-flex flex-column align-items-center">
    <h1 class="display-1">404</h1>
    <h2 class="display-2 text-center">La página no existe</h2>
  </div>
{% endblock %}

home/templates/home/error_500.html
{% extends 'base.html' %}
{% block title %}
  Valhalla 500
{% endblock %}
{% block content %}
  <div class="container d-flex flex-column align-items-center">
    <h1 class="display-1">500</h1>
    <h2 class="display-2 text-center">Hubo un error en el servidor</h2>
  </div>
{% endblock %}

home/templates/home/homepage.html
{% extends 'base.html' %}
{% block title %}
  Valhalla
{% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      {% for page in pages %}
        <div class="col-12 col-md-6 col-lg-4 my-2">
          <div class="card text-center">
            <div class="card-body">
              <h4 class="card-title">{{ page.name }}</h4>
              <a class="btn btn-primary btn-large" href="{{ page.url }}">Ir</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

recipes/templates/recipes/all_recipes.html
{% extends 'base.html' %}
{% block title %}
  Mis recetas
{% endblock %}
{% block content %}
  <div class="container">
    {% for category in category_list %}
      {% if category.recipes %}
        <div class="container my-5">
          <h1 class="display1">{{ category.name }}</h1>
          {% for recipe in category.recipes %}
            <h3 class="display3">{{ recipe.title }}</h3>
            {% if recipe.ingredients.all %}
              <ul>
                {% for ingredient in recipe.recipeingredient_set.all %}
                    <li>{{ ingredient.ingredient.name }} - {{ ingredient.main_quantity.normalize }} {{ ingredient.main_unit }}{% if ingredient.second_quantity %} ({{ ingredient.second_quantity.normalize }} {{ ingredient.second_unit }}){% endif %}</li>
                {% endfor %}
              </ul>
            {% endif %}
            {% if recipe.body %}
              <p class="text-break">{{ recipe.body|linebreaks }}</p>
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}

recipes/templates/recipes/category_form.html
{% extends './recipes_base.html' %}
{% load crispy_forms_tags %}
{% block recipes_content %}
<p>
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Enviar">
    <input type="submit" value="Cancelar" onclick="window.location.href='{% url 'recipes:category_list' %}';return false;">
  </form>
</p>
{% endblock %}

recipes/templates/recipes/category_list.html
{% extends './recipes_base.html' %}
{% block title %}
  Mis recetas
{% endblock %}
<!-- SUBHEADER -->
{% block subheader %}
  <li class="nav-item d-flex justify-content-end">
    <a href="{% url 'recipes:category_add' %}" class="nav-link"><i class="bi bi-plus-lg"></i> Añadir categoría</a>
  </li>
{% endblock %}
<!-- CONTENT -->
{% block recipes_content %}
  {% for category in category_list %}
    <a href="{% url 'recipes:recipe_list' category.id %}" class="text-decoration-none text-body">
      <div class="card m-2">
        <div class="card-body">
          <h4 class="card-title">{{ category.name }}</h4>
          <p class="text-muted">Elementos: {{ category.count }}</p>
        </div>
      </div>
    </a>
  {% endfor %}
  {% if no_category_count > 0 %}
    <a href="{% url 'recipes:recipe_list_no_category' %}" class="text-decoration-none text-body">
      <div class="card m-2">
        <div class="card-body">
          <h4 class="card-title">Sin categoría</h4>
          <p class="text-muted">Elementos: {{ no_category_count }}</p>
        </div>
      </div>
    </a>
  {% endif %}
{% endblock %}

recipes/templates/recipes/recipe_detail.html
{% extends './recipes_base.html' %}
<!-- HEADER -->
{% block header_left %}
  {% if recipe.category %}
    <a href="{% url 'recipes:recipe_list' recipe.category.id %}" class="link-secondary"><i class="bi bi-arrow-left" style="font-size: 1.5rem"></i></a>
  {% else %}
    <a href="{% url 'recipes:recipe_list_no_category' %}" class="link-secondary"><i class="bi bi-arrow-left" style="font-size: 1.5rem"></i></a>
  {% endif %}
{% endblock %}
<!-- SUBHEADER -->
{% block subheader %}
  <li class="nav-item d-flex justify-content-end">
    <a href="{% url 'admin:recipes_recipe_change' recipe.id %}" target="_blank" class="nav-link"><i class="bi bi-pencil-fill"></i> Editar receta</a>
  </li>
{% endblock %}
<!-- CONTENT -->
{% block recipes_content %}
  {% if recipe.ingredients.all %}
    <ul>
      {% for ingredient in recipe.recipeingredient_set.all %}
        <li>{{ ingredient.ingredient.name }} - {{ ingredient.main_quantity.normalize }} {{ ingredient.main_unit }}{% if ingredient.second_quantity %} ({{ ingredient.second_quantity.normalize }} {{ ingredient.second_unit }}){% endif %}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% if recipe.body %}
    <p class="text-break">{{ recipe.body|linebreaks }}</p>
  {% endif %}
  {% if recipe.related_recipes.all %}
    <h4>Recetas relacionadas</h4>
    <ul>
      {% for related_recipe in recipe.related_recipes.all %}
        <li>
          <a href="{% url 'recipes:recipe_detail' related_recipe.id %}">{{ related_recipe.title }}</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

recipes/templates/recipes/recipe_form.html
{% extends './recipes_base.html' %}
{% load crispy_forms_tags %}
{% block recipes_content %}
<p>
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Enviar">
    <input type="submit" value="Cancelar" onclick="window.location.href='{% url 'recipes:category_list' %}';return false;">
  </form>
</p>
{% endblock %}

recipes/templates/recipes/recipe_list.html
{% extends './recipes_base.html' %}
<!-- HEADER -->
{% block header_left %}
  <a href="{% url 'recipes:category_list' %}" class="link-secondary"><i class="bi bi-arrow-left" style="font-size: 1.5rem"></i></a>
{% endblock %}
<!-- SUBHEADER -->
{% block subheader %}
  {% if category %}
    <li class="nav-item d-flex justify-content-end">
      <a href="{% url 'admin:recipes_category_change' category.id %}" target="_blank" class="nav-link"><i class="bi bi-pencil-fill"></i> Editar categoría</a>
    </li>
  {% endif %}
{% endblock %}
<!-- CONTENT -->
{% block recipes_content %}
  {% url 'recipes:search_results' as search_url %}
  {% if request.path == search_url and recipe_list %}
    <p class="text-body-secondary">{{ recipe_list|length }} resultados para la búsqueda '{{ query }}'</p>
  {% endif %}
  {% for recipe in recipe_list %}
    <a href="{% url 'recipes:recipe_detail' recipe.id %}" class="text-decoration-none text-body">
      <div class="card m-2">
        <div class="card-body">
          <h4 class="card-title">{{ recipe.title }}</h4>
          {% if recipe.ingredients.all %}
            <ul>
                {% for ingredient in recipe.recipeingredient_set.all %}
                    <li>{{ ingredient.ingredient.name }} - {{ ingredient.main_quantity.normalize }} {{ ingredient.main_unit }}{% if ingredient.second_quantity %} ({{ ingredient.second_quantity.normalize }} {{ ingredient.second_unit }}){% endif %}</li>
                {% endfor %}
                {% if recipe.ingredients|length > 3 %}
                    <li>...</li>
                {% endif %}
            </ul>
          {% endif %}
          {% if recipe.body %}
            <p class="text-break">{{ recipe.body|truncatechars:200|linebreaks }}</p>
          {% endif %}
        </div>
      </div>
    </a>
  {% empty %}
    <p>
      {% url 'recipes:search_results' as search_url %}
      {% if request.path == search_url %}
        No hay resultados para la búsqueda '{{ query }}'
      {% else %}
        No hay recetas en esta categoría
      {% endif %}
    </p>
  {% endfor %}
{% endblock %}

recipes/templates/recipes/recipes_base.html
{% extends 'base.html' %}
{% block title %}
  {% if header_text %}
    Mis recetas | {{ header_text }}
  {% else %}
    Mis recetas
  {% endif %}
{% endblock %}
<!-- HEADER -->
{% block header_right %}
  <a href="{% url 'home:home' %}" class="link-secondary"><i class="bi bi-house-fill" style="font-size: 1.5rem"></i></a>
{% endblock %}
<!-- CONTENT -->
{% block content %}
  <!-- SUBHEADER -->
  <nav class="navbar">
    <div class="container-fluid justify-content-end">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-content"><i class="bi bi-list"></i></button>

      <div class="collapse navbar-collapse" id="navbar-content">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <form class="d-flex justify-content-end" action="{% url 'recipes:search_results' %}" method="get">
            <input type="text" placeholder="Buscar una receta" name="query" />
            <button type="submit" class="btn btn-primary"><i class="bi bi-search"></i></button>
          </form>
          {% block subheader %}

          {% endblock %}
          <li class="nav-item d-flex justify-content-end">
            <a href="{% url 'recipes:recipe_add' %}" class="nav-link"><i class="bi bi-plus-lg"></i> Añadir receta</a>
          </li>
          <li class="nav-item d-flex justify-content-end">
            <a href="{% url 'recipes:all_recipes' %}" target="_blank" class="nav-link"><i class="bi bi-file-text"></i> Ver todas las recetas</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container-md">
    {% block recipes_content %}

    {% endblock %}
  </div>
{% endblock %}